services:
  - type: worker
    name: discord-bot
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CREW_NAME
        sync: false
